name: livego_app
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  video_player: ^2.8.1
  path_provider: ^2.1.1
  cached_network_image: ^3.3.1 # AGAR RINGAN
flutter:
  uses-material-design: true
